// 旅遊日語。點任一句會放大成「給店員看」的大字卡
// jp = 日文（給對方看）、rm = 羅馬拼音（自己唸）、tw = 中文
(function () {
  const p = (tw, jp, rm, note) => ({ tw, jp, rm, note: note || '' });

  window.PHRASES = [
    {
      cat: '🌱 吃素必備', star: true, items: [
        p('我吃素。不吃肉、魚、海鮮，也不吃柴魚和雞高湯。',
          '私はベジタリアンです。肉・魚・魚介類、かつおだし・鶏がらスープも食べられません。',
          'watashi wa bejitarian desu. niku, sakana, gyokairui, katsuo-dashi, toriragara-sūpu mo taberaremasen.',
          '日本很多湯頭用柴魚，一定要特別講'),
        p('我也不吃蔥和蒜。',
          'ねぎ・玉ねぎ・にんにくも食べられません。',
          'negi, tamanegi, ninniku mo taberaremasen.'),
        p('請問有素食餐點嗎？',
          'ベジタリアン向けのメニューはありますか？',
          'bejitarian muke no menyū wa arimasu ka?'),
        p('這道菜裡面有肉或魚嗎？',
          'これに肉や魚は入っていますか？',
          'kore ni niku ya sakana wa haitte imasu ka?'),
        p('這個湯頭是用柴魚還是昆布？',
          'このだしは、かつおですか？昆布ですか？',
          'kono dashi wa, katsuo desu ka? konbu desu ka?',
          '昆布だし＝素的；かつおだし＝柴魚'),
        p('可以幫我去掉蔥和蒜嗎？',
          'ねぎとにんにくを抜いてもらえますか？',
          'negi to ninniku o nuite moraemasu ka?'),
        p('可以幫我把肉換成蔬菜或豆腐嗎？',
          'お肉を野菜か豆腐に替えてもらえますか？',
          'oniku o yasai ka tōfu ni kaete moraemasu ka?'),
        p('我吃素，可以不點餐只坐在一起嗎？',
          '私はベジタリアンなので、注文せずに一緒に座ってもいいですか？',
          'watashi wa bejitarian na node, chūmon sezu ni issho ni suwatte mo ii desu ka?',
          '同行的人要吃肉時很好用'),
        p('那我只點飲料就好。',
          'では、飲み物だけ注文します。',
          'dewa, nomimono dake chūmon shimasu.',
          '不點餐被拒絕時的折衷做法'),
        p('可以自己帶食物進來嗎？',
          '持ち込みはできますか？',
          'mochikomi wa dekimasu ka?'),
        p('沒關係，那我不點這個。',
          '大丈夫です。では、これはやめておきます。',
          'daijōbu desu. dewa, kore wa yamete okimasu.',
          '問完發現不能吃時，禮貌收尾'),
        p('這附近有素食餐廳嗎？',
          'この近くにベジタリアンのお店はありますか？',
          'kono chikaku ni bejitarian no omise wa arimasu ka?'),
        p('這個便當裡面有肉嗎？',
          'このお弁当に肉は入っていますか？',
          'kono obentō ni niku wa haitte imasu ka?',
          '便利商店、車站便當都能問'),
      ],
    },
    {
      cat: '🍽️ 點餐', items: [
        p('我想要一個這個。', 'これを一つください。', 'kore o hitotsu kudasai.', '指著菜單或食物講就好'),
        p('請給我兩個。', 'これを二つください。', 'kore o futatsu kudasai.'),
        p('請給我菜單。', 'メニューをお願いします。', 'menyū o onegai shimasu.'),
        p('有中文或英文菜單嗎？', '中国語か英語のメニューはありますか？', 'chūgokugo ka eigo no menyū wa arimasu ka?'),
        p('推薦哪一個？', 'おすすめはどれですか？', 'osusume wa dore desu ka?'),
        p('內用。', 'ここで食べます。', 'koko de tabemasu.'),
        p('外帶。', '持ち帰りです。', 'mochikaeri desu.'),
        p('兩位。', '二人です。', 'futari desu.'),
        p('要等多久？', 'どのくらい待ちますか？', 'dono kurai machimasu ka?'),
        p('可以續點嗎？', '追加できますか？', 'tsuika dekimasu ka?'),
        p('麻煩結帳。', 'お会計をお願いします。', 'okaikei o onegai shimasu.'),
        p('很好吃，謝謝。', 'とても美味しかったです。ごちそうさまでした。', 'totemo oishikatta desu. gochisōsama deshita.'),
      ],
    },
    {
      cat: '🏪 便利商店・外帶', items: [
        p('要加熱嗎？→ 麻煩加熱。', '温めてください。', 'atatamete kudasai.', '店員問「温めますか？」時這樣回'),
        p('不用加熱。', '温めなくて大丈夫です。', 'atatamenakute daijōbu desu.'),
        p('請給我筷子（湯匙）。', 'お箸（スプーン）をください。', 'ohashi (supūn) o kudasai.'),
        p('請給我袋子。', '袋をください。', 'fukuro o kudasai.', '日本袋子多半要另外付費'),
        p('要分開裝嗎？→ 一起裝就好。', '一緒で大丈夫です。', 'issho de daijōbu desu.'),
        p('可以在這裡吃嗎？', 'ここで食べてもいいですか？', 'koko de tabete mo ii desu ka?'),
        p('垃圾可以丟這裡嗎？', 'ゴミはここに捨ててもいいですか？', 'gomi wa koko ni sutete mo ii desu ka?'),
      ],
    },
    {
      cat: '🎢 樂園・景點', items: [
        p('整理券要在哪裡領？', '整理券はどこでもらえますか？', 'seiriken wa doko de moraemasu ka?', 'USJ 任天堂區、熱門設施會用到'),
        p('現在要排多久？', '今、待ち時間はどのくらいですか？', 'ima, machi-jikan wa dono kurai desu ka?'),
        p('單人排隊在哪裡？', 'シングルライダーはどこですか？', 'shinguru-raidā wa doko desu ka?', '侏羅紀公園走單人通道時用'),
        p('這個要另外買票嗎？', 'これは別料金ですか？', 'kore wa betsu-ryōkin desu ka?'),
        p('入口（出口）在哪裡？', '入口（出口）はどこですか？', 'iriguchi (deguchi) wa doko desu ka?'),
        p('置物櫃在哪裡？', 'ロッカーはどこですか？', 'rokkā wa doko desu ka?'),
        p('請問今天幾點關園？', '今日は何時までですか？', 'kyō wa nanji made desu ka?'),
        p('可以幫我蓋紀念章嗎？', 'スタンプを押してもらえますか？', 'sutanpu o oshite moraemasu ka?'),
      ],
    },
    {
      cat: '🏨 住宿', items: [
        p('我要入住（辦理登記）。', 'チェックインをお願いします。', 'chekku-in o onegai shimasu.'),
        p('我要退房。', 'チェックアウトをお願いします。', 'chekku-auto o onegai shimasu.'),
        p('我訂了房，這是我的名字。', '予約しています。こちらが私の名前です。', 'yoyaku shite imasu. kochira ga watashi no namae desu.'),
        p('可以先寄放行李嗎？', '荷物を預かってもらえますか？', 'nimotsu o azukatte moraemasu ka?'),
        p('退房後可以寄放行李嗎？', 'チェックアウト後も荷物を預かってもらえますか？', 'chekku-auto go mo nimotsu o azukatte moraemasu ka?'),
        p('早餐幾點開始？', '朝食は何時からですか？', 'chōshoku wa nanji kara desu ka?'),
        p('早餐有素食嗎？', '朝食にベジタリアンのメニューはありますか？', 'chōshoku ni bejitarian no menyū wa arimasu ka?'),
        p('溫泉幾點到幾點？', '温泉は何時から何時までですか？', 'onsen wa nanji kara nanji made desu ka?'),
        p('可以延後退房嗎？', 'レイトチェックアウトはできますか？', 'reito-chekku-auto wa dekimasu ka?'),
        p('可以幫我寄行李到下一間飯店嗎？', '荷物を次のホテルに送ってもらえますか？', 'nimotsu o tsugi no hoteru ni okutte moraemasu ka?', '關西飯店間的宅急便很方便'),
        p('房間的 Wi-Fi 密碼是什麼？', '部屋のWi-Fiのパスワードを教えてください。', 'heya no waifai no pasuwādo o oshiete kudasai.'),
        p('可以多給我一條毛巾嗎？', 'タオルをもう一枚もらえますか？', 'taoru o mō ichimai moraemasu ka?'),
      ],
    },
    {
      cat: '🔢 數字與金錢', items: [
        p('1・2・3', '一（いち）・二（に）・三（さん）', 'ichi / ni / san'),
        p('4・5・6', '四（よん）・五（ご）・六（ろく）', 'yon / go / roku'),
        p('7・8・9・10', '七（なな）・八（はち）・九（きゅう）・十（じゅう）', 'nana / hachi / kyū / jū'),
        p('100・1000・10000', '百（ひゃく）・千（せん）・一万（いちまん）', 'hyaku / sen / ichiman', '日幣看到 1,000 就唸 せん'),
        p('¥100', '百円（ひゃくえん）', 'hyaku-en'),
        p('¥500', '五百円（ごひゃくえん）', 'gohyaku-en'),
        p('¥1,000', '千円（せんえん）', 'sen-en'),
        p('¥3,800', '三千八百円（さんぜんはっぴゃくえん）', 'sanzen happyaku-en'),
        p('¥10,000', '一万円（いちまんえん）', 'ichiman-en'),
        p('一個・兩個・三個', '一つ（ひとつ）・二つ（ふたつ）・三つ（みっつ）', 'hitotsu / futatsu / mittsu', '點餐數量用這組，不是 いち・に・さん'),
        p('一位・兩位', '一人（ひとり）・二人（ふたり）', 'hitori / futari'),
        p('一杯・一份', '一杯（いっぱい）・一枚（いちまい）', 'ippai / ichimai'),
        p('總共多少錢？', '全部でいくらですか？', 'zenbu de ikura desu ka?'),
        p('這是含稅價嗎？', 'これは税込みですか？', 'kore wa zeikomi desu ka?', '税込＝含稅、税抜＝未稅'),
        p('可以分開付嗎？', '別々でお願いします。', 'betsubetsu de onegai shimasu.', '和旅伴各付各的'),
        p('一起付。', '一緒でお願いします。', 'issho de onegai shimasu.'),
        p('請給我收據。', 'レシートをください。', 'reshīto o kudasai.'),
        p('請給我統一發票（收據抬頭）。', '領収書をお願いします。', 'ryōshūsho o onegai shimasu.', '報帳用的正式收據'),
        p('我只有一萬元紙鈔，可以嗎？', '一万円札しかないのですが、大丈夫ですか？', 'ichiman-en satsu shika nai no desu ga, daijōbu desu ka?'),
        p('找錢好像不對。', 'おつりが違うようです。', 'otsuri ga chigau yō desu.'),
        p('這個有打折嗎？', 'これは割引がありますか？', 'kore wa waribiki ga arimasu ka?', '半額＝半價、○％引き＝打折'),
        p('哪裡可以換錢（領錢）？', '両替（ATM）はどこですか？', 'ryōgae (ētīemu) wa doko desu ka?', '日本 ATM 認台灣金融卡的以 7-11、郵局為主'),
      ],
    },
    {
      cat: '🛍️ 購物・退稅', items: [
        p('這個多少錢？', 'これはいくらですか？', 'kore wa ikura desu ka?'),
        p('可以刷卡嗎？', 'カードは使えますか？', 'kādo wa tsukaemasu ka?'),
        p('可以用西瓜卡付嗎？', 'Suicaで払えますか？', 'suika de haraemasu ka?'),
        p('我要退稅，這是護照。', '免税でお願いします。パスポートです。', 'menzei de onegai shimasu. pasupōto desu.'),
        p('可以試穿嗎？', '試着してもいいですか？', 'shichaku shite mo ii desu ka?'),
        p('有大一號的嗎？', 'ワンサイズ大きいのはありますか？', 'wan-saizu ōkii no wa arimasu ka?'),
        p('這個有別的顏色嗎？', 'これの別の色はありますか？', 'kore no betsu no iro wa arimasu ka?'),
        p('可以幫我包成禮物嗎？', 'プレゼント用に包んでもらえますか？', 'purezento yō ni tsutsunde moraemasu ka?'),
        p('不用袋子，謝謝。', '袋はいりません。ありがとうございます。', 'fukuro wa irimasen. arigatō gozaimasu.'),
        p('我再看看，謝謝。', '少し見てみます。ありがとうございます。', 'sukoshi mite mimasu. arigatō gozaimasu.'),
      ],
    },
    {
      cat: '🚃 交通', items: [
        p('請問去這裡要怎麼走？', 'ここへはどうやって行きますか？', 'koko e wa dō yatte ikimasu ka?', '配合地圖或 App 畫面一起給對方看'),
        p('去嵐山的月台是幾號？', '嵐山行きのホームは何番ですか？', 'arashiyama-yuki no hōmu wa nanban desu ka?'),
        p('這班車有到這裡嗎？', 'この電車はここに行きますか？', 'kono densha wa koko ni ikimasu ka?'),
        p('下一班是幾點？', '次は何時ですか？', 'tsugi wa nanji desu ka?'),
        p('西瓜卡可以用嗎？', 'Suicaは使えますか？', 'suika wa tsukaemasu ka?'),
        p('要在哪裡換車？', 'どこで乗り換えますか？', 'doko de norikaemasu ka?'),
        p('請幫我叫計程車。', 'タクシーを呼んでもらえますか？', 'takushī o yonde moraemasu ka?'),
        p('麻煩到這個地址。', 'この住所までお願いします。', 'kono jūsho made onegai shimasu.', '給司機看地址畫面'),
        p('投幣置物櫃在哪裡？', 'コインロッカーはどこですか？', 'koin-rokkā wa doko desu ka?'),
      ],
    },
    {
      cat: '❓ 問路・基本', items: [
        p('廁所在哪裡？', 'トイレはどこですか？', 'toire wa doko desu ka?'),
        p('不好意思（叫人時）。', 'すみません。', 'sumimasen.'),
        p('謝謝。', 'ありがとうございます。', 'arigatō gozaimasu.'),
        p('請問一下。', 'ちょっとお聞きしたいのですが。', 'chotto okiki shitai no desu ga.'),
        p('我聽不懂日文，可以寫下來嗎？', '日本語が分かりません。書いてもらえますか？', 'nihongo ga wakarimasen. kaite moraemasu ka?'),
        p('可以說慢一點嗎？', 'ゆっくり話してもらえますか？', 'yukkuri hanashite moraemasu ka?'),
        p('可以拍照嗎？', '写真を撮ってもいいですか？', 'shashin o totte mo ii desu ka?'),
        p('可以幫我們拍張照嗎？', '写真を撮ってもらえますか？', 'shashin o totte moraemasu ka?'),
        p('幾點關門？', '何時までですか？', 'nanji made desu ka?'),
        p('我迷路了。', '道に迷いました。', 'michi ni mayoimashita.'),
      ],
    },
    {
      cat: '🆘 緊急', items: [
        p('我身體不舒服。', '体調が悪いです。', 'taichō ga warui desu.'),
        p('附近有藥局嗎？', '近くに薬局はありますか？', 'chikaku ni yakkyoku wa arimasu ka?'),
        p('我想要胃藥（頭痛藥、感冒藥）。', '胃薬（頭痛薬・風邪薬）がほしいです。', 'igusuri (zutsūyaku, kazegusuri) ga hoshii desu.'),
        p('我想要 OK 繃（生理用品）。', '絆創膏（生理用品）がほしいです。', 'bansōkō (seiri-yōhin) ga hoshii desu.'),
        p('附近有醫院嗎？', '近くに病院はありますか？', 'chikaku ni byōin wa arimasu ka?'),
        p('請幫我叫救護車。', '救急車を呼んでください。', 'kyūkyūsha o yonde kudasai.'),
        p('我的東西掉了。', '落とし物をしました。', 'otoshimono o shimashita.'),
        p('我的護照不見了。', 'パスポートをなくしました。', 'pasupōto o nakushimashita.'),
        p('請幫我報警。', '警察を呼んでください。', 'keisatsu o yonde kudasai.'),
        p('我和朋友走散了。', '友達とはぐれました。', 'tomodachi to haguremashita.'),
      ],
    },
  ];
})();
